Fixes the following error when using a date as MFA. The date is represented as datetime object which doesn't have a strip() function. Casting as a string fixes the issue.
  File "src/smartschool/credentials.py", line 27, in validate
    new_value = (original_value or "").strip()

AttributeError: 'datetime.date' object has no attribute 'strip'